//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beast.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beast.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beast MUD Editor.
        /// </summary>
        internal static string BaseTitle {
            get {
                return ResourceManager.GetString("BaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Place?.
        /// </summary>
        internal static string DeletePlaceDialog_Caption {
            get {
                return ResourceManager.GetString("DeletePlaceDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the place at {0}, {1}?.
        /// </summary>
        internal static string DeletePlaceDialog_MsgFormat {
            get {
                return ResourceManager.GetString("DeletePlaceDialog_MsgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string DocumentSaveDialog_Caption {
            get {
                return ResourceManager.GetString("DocumentSaveDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has unsaved changes. Do you want to save &apos;{0}&apos; first before closing?.
        /// </summary>
        internal static string DocumentSaveDialog_MsgFormat {
            get {
                return ResourceManager.GetString("DocumentSaveDialog_MsgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string DocumentTitleFormat {
            get {
                return ResourceManager.GetString("DocumentTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string FileDirtyIndicator {
            get {
                return ResourceManager.GetString("FileDirtyIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beast MUD files|*.beast.
        /// </summary>
        internal static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Beast MUD Project.
        /// </summary>
        internal static string OpenProjectDialog_Title {
            get {
                return ResourceManager.GetString("OpenProjectDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:{0}, Y:{1}.
        /// </summary>
        internal static string PlaceLocationFormat {
            get {
                return ResourceManager.GetString("PlaceLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PlacePropertyEditorName {
            get {
                return ResourceManager.GetString("PlacePropertyEditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins.
        /// </summary>
        internal static string PluginsDirectory {
            get {
                return ResourceManager.GetString("PluginsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeastMUD.
        /// </summary>
        internal static string RootFolder {
            get {
                return ResourceManager.GetString("RootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project Failed.
        /// </summary>
        internal static string SaveProjectDialog_ProjectEmpty_Caption {
            get {
                return ResourceManager.GetString("SaveProjectDialog_ProjectEmpty_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or create a project before attempting to save..
        /// </summary>
        internal static string SaveProjectDialog_ProjectEmpty_Msg {
            get {
                return ResourceManager.GetString("SaveProjectDialog_ProjectEmpty_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}{2}.
        /// </summary>
        internal static string TitleFormat {
            get {
                return ResourceManager.GetString("TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones.
        /// </summary>
        internal static string ZoneListEditorName {
            get {
                return ResourceManager.GetString("ZoneListEditorName", resourceCulture);
            }
        }
    }
}
